crate/cratedb-examples

spikes/kafka-flink/.gitignore
spikes/kafka-flink/Makefile
spikes/kafka-flink/README.Unix.rst
spikes/kafka-flink/README.Windows.rst
spikes/kafka-flink/README.rst
spikes/kafka-flink/docker-compose.yml
spikes/kafka-flink/notes.rst

Hi there,
this is the baseline infrastructure for the tutorial about »_Processing IIoT data with Apache Kafka, Apache Flink and CrateDB_« from the »_Building IoT applications with open-source components_« series of articles.
It gets accompanied by the https://github.com/crate/cratedb-flink-jobs repository.
With kind regards,
Andreas.
cc @carlotasoto

Add infrastructure for "Kafka, Flink and CrateDB" tutorial

---

.github/workflows/tests-npgsql.yml
by-language/csharp-npgsql/README.rst

This is all related to the [`csharp-npgsql` project](https://github.com/crate/cratedb-examples/tree/538e1601105/by-language/csharp-npgsql) within this repository.
- The GHA recipe has not been updated when refactoring the directory layout the other day.
- Add path filter. In this manner, corresponding CI jobs will only be started on changes within the relevant directories. It does not make sense to run jobs for a specific area every time changes are made in a completely different area.
- Use CrateDB 4.8.3, 4.8.4, and nightly
- Use most recent versions of GHA recipes

CI: Fix, improve, and modernize `csharp-npgsql` project

---

by-language/java-jooq/README.rst
by-language/java-jooq/backlog.rst

Hi again,
the documentation improvements for the jOOQ example have been split off from GH-11, and are submitted hereby instead. 
There has been another round of edits, and a few of them may have some annotations from my side. On others, _you_ may want to have a second look, or also add some comments or questions.
You can directly view the rendered variants of the documents, it is probably more pleasant to read [^1][^2].
With kind regards,
Andreas.
[^1]: https://github.com/crate/cratedb-examples/blob/amo/jooq/improve-docs/by-language/java-jooq/README.rst
[^2]: https://github.com/crate/cratedb-examples/blob/amo/jooq/improve-docs/by-language/java-jooq/backlog.rst

Java/jOOQ: Improve documentation

---

.github/workflows/test-kafka-flink.yml
stacks/kafka-flink/README.rst
stacks/kafka-flink/docker-compose.yml
stacks/kafka-flink/test.sh

Hi again,
as promised at GH-20, this patch adds a basic end-to-end test for the Kafka/Flink/CrateDB stack, also running it on CI/GHA. I am sad that it is a Bash script, but this is still the most compact yet coherent representation of the recipe. The outcome will be a description like this, in the error case with an exitcode != 0.
```
=========================
Verifying data in CrateDB
=========================
SUCCESS: Database table contains expected number of 5000 records.
```
```
=========================
Verifying data in CrateDB
=========================
ERROR:   Expected database table to contain 5000 records, but it contains 0 records.
```
With kind regards,
Andreas.

Kafka/Flink: Add end-to-end test

---

stacks/kafka-flink/.env
stacks/kafka-flink/README.rst
stacks/kafka-flink/docker-compose.yml
stacks/kafka-flink/test.sh

Kafka/Flink: Properly use pre-release `cratedb-flink-jobs-0.3dev1`
based on https://github.com/crate/cratedb-flink-jobs/tree/mt/update-flink-jobs

Modernize kafka-flink-cratedb job to run with flink 1.16.1

---

by-language/java-jdbc/BasicPostgresCrateDB.java
by-language/java-jdbc/README.rst
by-language/java-jdbc/pom.xml

Hi there,
this patch aims to improve the canonical Java/JDBC example to also cover demonstrating usage with CrateDB Cloud.
- Add [JCommander](https://jcommander.org/) for command line argument parsing
- Skip provisioning a database schema, query `sys.summits` instead
- Improve error handling
With kind regards,
Andreas.

Java/JDBC: Adjustments to also demonstrate usage with CrateDB Cloud

---

.github/dependabot.yml
.github/workflows/test-java-jooq.yml
.github/workflows/test-npgsql.yml

In order to accomodate recent Dependabot notices, this improves the test coverage beforehand.
- Rename npgsql workflow file
- Run tests for `java-jooq` example
- Enable Dependabot to check GitHub Action packages for freshness

CI: Improve configuration

---

stacks/kafka-flink/.env

Use the new `0.3.` release instead of the temp 0.3-dev1.
Fixes: https://github.com/crate/cratedb-examples/issues/6

Use new release of cratedb-flink-jobs

---

framework/langchain/conversational_memory.ipynb
framework/langchain/conversational_memory.py
framework/langchain/document_loader.ipynb
framework/langchain/document_loader.py
framework/langchain/readme.md
framework/langchain/requirements.txt
framework/langchain/vector_search.ipynb
framework/langchain/vector_search.py

We have been looking into making [LangChain](https://www.langchain.com/) work together with CrateDB. This patch adds corresponding example programs and Jupyter Notebooks.
- https://github.com/crate-workbench/langchain/pull/1
Readme, rendered by GitHub: [LangChain and CrateDB](https://github.com/crate/cratedb-examples/blob/amo/framework-langchain/framework/langchain/readme.md)
both the basic example programs, and the Jupyter Notebooks.
/cc @marijaselakovic, @hammerhead, @seut, @ckurze

[LangChain] Add example programs and notebooks

---

.github/workflows/test-langchain.yml
framework/langchain/pyproject.toml
framework/langchain/test.py
framework/langchain/vector_search.ipynb

Building upon the test infrastructure added with GH-97, this patch intends to fix a few last flaws within the Jupyter Notebook `vector_search.ipynb`, primarily to make the software tests succeed.
It also invokes corresponding tests on CI/GHA now.
/cc @ckurze, @WalBeh

[LangChain] Fix testing Jupyter Notebook `vector_search.ipynb`

---

.github/dependabot.yml
.github/workflows/test-java-jdbc.yml
.github/workflows/test-java-jooq.yml
.github/workflows/test-kafka-flink.yml
.github/workflows/test-langchain.yml
.github/workflows/test-npgsql.yml
.github/workflows/test-php-amphp.yml
.github/workflows/test-php-pdo.yml
.github/workflows/test-python-sqlalchemy.yml
.github/workflows/test-ruby.yml
.github/workflows/testcontainers-java.yml

- Dependabot: Add `/framework/{langchain,mlflow}` directories
- Dependabot: Schedule to run weekly
- Reformat `on:` / trigger section
- Schedule all established jobs to run each night. _Only when doing it this way, we will have a chance of getting notified
properly about any changes / regressions. Otherwise, they will go unnoticed, because, well, there is no other activity on the CI job._

CI: A few adjustments, mostly about scheduling

---

.github/workflows/test-java-jdbc.yml
.github/workflows/test-java-jooq.yml
.github/workflows/test-langchain.yml
.github/workflows/test-npgsql.yml
.github/workflows/test-php-amphp.yml
.github/workflows/test-php-pdo.yml
.github/workflows/test-python-sqlalchemy.yml
.github/workflows/test-ruby.yml
.github/workflows/testcontainers-java.yml
by-language/python-sqlalchemy/insert_dask.py
by-language/python-sqlalchemy/insert_pandas.py

Bump a few language versions on CI, where possible.
- Java 11 vs. 17
- PHP 8.3
- Python 3.12
- Ruby 3.2
/cc @hammerhead, @hlcianfagna, @karynzv, @WalBeh

CI: Update language versions

---

README.rst
requirements.txt

~~Verifies that the recent updates to the `ngr` test runner do not break anything, when updating to version 0.0.2.~~ Update to ngr 0.0.2.
- https://github.com/pyveci/pueblo/pull/7

CI: Update to ngr 0.0.2

---

.github/dependabot.yml
.github/workflows/test-automl.yml
topic/machine-learning/classification-automl/automl_classification_with_pycaret.ipynb
topic/machine-learning/classification-automl/automl_classification_with_pycaret.py
topic/machine-learning/classification-automl/backlog.md
topic/machine-learning/classification-automl/pyproject.toml
topic/machine-learning/classification-automl/requirements-dev.txt
topic/machine-learning/classification-automl/requirements.txt
topic/machine-learning/classification-automl/test.py
topic/machine-learning/mlops-mlflow/requirements-dev.txt

Building upon recent improvements to the test infrastructure for Jupyter Notebooks, this brings corresponding tests to the PyCaret example, superseding GH-124.
- GH-125
- GH-131

ML: Add software tests and CI recipe to AutoML/PyCaret example

---

.github/workflows/test-mlflow.yml

CI: Use Python 3.11 for AutoML material

---

.github/workflows/test-npgsql.yml
requirements.txt

The testmatrix for the Npgsql example had a flaw. The .NET framework version was not selected appropriately.
- GH-172
- GH-165
- GH-169

Npgsql: Fix test matrix, and add .NET 8.0

---

topic/machine-learning/automl/README.md
topic/machine-learning/automl/automl_classification_with_pycaret.ipynb
topic/machine-learning/automl/automl_classification_with_pycaret.py
topic/machine-learning/automl/automl_timeseries_forecasting_with_pycaret.ipynb
topic/machine-learning/automl/automl_timeseries_forecasting_with_pycaret.py
topic/machine-learning/automl/backlog.md
topic/machine-learning/automl/pyproject.toml
topic/machine-learning/automl/test.py

For an upcoming presentation, this patch sands the AutoML notebooks a bit more, for improved usability. It is specifically about making it easier to run them on the Google Colab computing environment.
- Improve Python dependency definition by inlining it into the notebook.
- Improve database connectivity definition by only using a single configuration value.

AutoML: Improve notebooks for easier usage on Google Colab

---

.github/workflows/test-npgsql.yml
by-language/csharp-npgsql/README.rst

While adding .NET 8.x, we discovered that the testing on .NET 5.x is broken:
> The tests are flawed: They signal "green" status on CI, but actually no tests are compiled and executed.
This patch just removes .NET 5.x from the test matrix.
- https://github.com/crate/cratedb-examples/pull/169#discussion_r1413085186 ff.

Npgsql: Stop running tests on .NET framework version 5.x

---

.github/workflows/apache-superset.yml
framework/apache-superset/conftest.py
framework/apache-superset/requirements.txt
framework/apache-superset/superset_config.py
framework/apache-superset/test.py

This patch aims to add Apache Superset 3 and Python 3.12 to the CI test matrix, extending GH-217.

Apache Superset: Also verify Superset 3

---

.github/workflows/apache-superset.yml
.gitignore
framework/apache-superset/README.md
framework/apache-superset/conftest.py
framework/apache-superset/data.sql
framework/apache-superset/pyproject.toml
framework/apache-superset/requirements-test.txt
framework/apache-superset/requirements.txt
framework/apache-superset/superset_config.py
framework/apache-superset/test.py
framework/apache-superset/util.py

This patch includes a few basic test cases having conversations with the Apache Superset UI and HTTP API, using a database connection to CrateDB. It is meant to monitor connectivity works, and doesn't break with future releases of both Apache Superset and CrateDB. By running the integration tests each night, the monitoring will be durable.
The README document [Verify Apache Superset with CrateDB](https://github.com/crate/cratedb-examples/blob/b2a01867e7/framework/apache-superset/README.md) included here is a mini tutorial which walks you through the steps needed to setup an instance of Apache Superset on your machine, and connect it to CrateDB. If you don't want to clone any repository to get started, effectively all you need are the [requirements.txt] and [superset_config.py] files.
/cc …

Apache Superset: Verify connectivity to CrateDB with basic integration tests

---

.github/workflows/test-npgsql.yml
by-language/csharp-npgsql/demo.csproj

Npgsql 8.0.0 was released in November 2023. Npgsql 8.0.1 was released in December 2023.
- https://www.npgsql.org/doc/release-notes/8.0.html
- https://github.com/npgsql/npgsql/issues/5503
- https://github.com/crate/crate/issues/15281
- https://github.com/crate/crate-qa/pull/289
- https://github.com/crate/cratedb-examples/pull/169
- [CrateDB 5.5 not working out of the box with Npgsql 8: A PostgreSQL type with the name 'unknown' was not found in the current database info](https://community.cratedb.com/t/cratedb-5-5-not-working-out-of-the-box-with-npgsql-8-a-postgresql-type-with-the-name-unknown-was-not-found-in-the-current-database-info/1689)
- https://github.com/crate/crate/pull/15291
- https://github.com/crate/cratedb-examples/pull/165
- https://github.com/crate/cratedb-examples/pull/195

CI: Add Npgsql 8.0.1 to test matrix

---

by-language/python-sqlalchemy/README.rst
by-language/python-sqlalchemy/async_streaming.py
by-language/python-sqlalchemy/async_table.py
by-language/python-sqlalchemy/requirements.txt
by-language/python-sqlalchemy/sync_table.py
by-language/python-sqlalchemy/test.py

The `sqlalchemy-cratedb` package supports the vanilla HTTP-based transport using `urllib3` (status quo), and the standard PostgreSQL drivers `asyncpg` and `psycopg` (improvement).
This patch demonstrates and verifies the functionality on behalf of corresponding example programs.
- https://github.com/crate-workbench/sqlalchemy-cratedb/pull/11

Python/SQLAlchemy: Demonstrate support for `asyncpg` and `psycopg3`

---

topic/machine-learning/llm-langchain/pyproject.toml

> Pyarrow will become a required dependency of pandas in the next major release of pandas 
> (pandas 3.0), (to allow more performant data types, such as the Arrow string type, and 
> better interoperability with other libraries) but was not found to be installed on your
> system. If this would cause problems for you, please provide us feedback at
> https://github.com/pandas-dev/pandas/issues/54466.

LLM: Fix LangChain warning about pandas 3.0 and PyArrow

---

.github/workflows/test-python-sqlalchemy.yml
by-language/python-sqlalchemy/insert_dask.py
by-language/python-sqlalchemy/insert_pandas.py
by-language/python-sqlalchemy/requirements-dev.txt

`pandas._testing.makeTimeDataFrame` got removed starting wih pandas 2.2.0.
- https://github.com/pyveci/pueblo/pull/59
- https://github.com/crate/cratedb-examples/pull/236

Python: Fix deprecation of `pandas._testing.makeTimeDataFrame`

---

topic/machine-learning/llm-langchain/pyproject.toml

Maintaining a list of individual Jupyter Notebook cells to suppress output comparison is just not sustainable. Let's turn that off.

LLM: Turn off validating notebook cell outputs

---

.github/workflows/test-langchain.yml
.github/workflows/test-python-sqlalchemy.yml

1fe608d36 and fc26c7a399 temporarily downgraded to CrateDB 5.5.3. This patch reverts those changes, now that nightly builds work well again.
Thank you very much for the quick fix.
- https://github.com/crate/crate/pull/15408

Python/LLM: Use CrateDB nightly again, resolving woes with JDK 21.0.2

---

topic/machine-learning/automl/requirements-dev.txt
topic/machine-learning/automl/requirements.txt
topic/machine-learning/llm-langchain/requirements-dev.txt
topic/machine-learning/mlops-mlflow/requirements-dev.txt
topic/machine-learning/mlops-mlflow/requirements.txt

Dependency update for notebook educational & QA folders about ML concerns. [cratedb-toolkit 0.0.3](https://github.com/crate-workbench/cratedb-toolkit/releases/tag/v0.0.3) has been released last week.

ML: Update to mlflow-cratedb@main, and cratedb-toolkit 0.0.3

---

framework/apache-superset/test.py

UI wording changed slightly within the 3.x release series, and needed an adjustment.
- https://github.com/crate/cratedb-examples/actions/runs/7649293830/job/20843463191#step:7:257

Apache Superset 3: Fix UI software test

---

.github/workflows/dataframe-dask.yml
.github/workflows/dataframe-pandas.yml
.github/workflows/framework-apache-superset.yml
.github/workflows/lang-java-jooq.yml
.github/workflows/lang-java-maven.yml
.github/workflows/lang-npgsql.yml
.github/workflows/lang-php-amphp.yml
.github/workflows/lang-php-pdo.yml
.github/workflows/lang-python-sqlalchemy.yml
.github/workflows/lang-ruby.yml
.github/workflows/ml-automl.yml
.github/workflows/ml-langchain.yml
.github/workflows/ml-mlflow.yml
.github/workflows/stack-kafka-flink.yml
.github/workflows/testing-testcontainers-java.yml

With a growing list of integrations to be validated, this patch attempts to improve coherency, better discriminating between different topic domains by prefixing the corresponding GHA workflow recipe files, using:
- `dataframe-`
- `framework-`
- `lang-`
- `ml-`
- `stack-`
- `testing-`
Unfortunately, we can't use subdirectories for that purpose.
- GH-272
- [Feature request: allow workflow configuration in sub-folders #18055](https://github.com/orgs/community/discussions/18055)
The total count on integration tests is 41. Just one more!
/cc @marijaselakovic, @surister, @ckurze

CI: Refactor GHA workflow recipes. Naming things.

---

.github/dependabot.yml
.github/workflows/framework-apache-superset.yml
.github/workflows/lang-java-jooq.yml
.github/workflows/lang-java-maven.yml
.github/workflows/lang-npgsql.yml
.github/workflows/lang-php-amphp.yml
.github/workflows/lang-php-pdo.yml
.github/workflows/lang-ruby.yml
.github/workflows/ml-automl.yml
.github/workflows/ml-langchain.yml
.github/workflows/ml-mlflow.yml
.github/workflows/stack-kafka-flink.yml

Following up on GH-273, this patch further improves the CI configuration.
- Reschedule ml-automl job to run at 6 o'clock, three hours later
- Reconfigure CrateDB container to use `CRATE_HEAP_SIZE: 4g`
- Align GHA recipes about CrateDB container configuration
- Add Apache Superset to Dependabot configuration
- Let Dependabot drive version compliance checks for Apache Superset

CI: Various improvements

---

README.md

Text-only is boring, and this repository will probably never have a dedicated representation as a slot within the documentation, so this patch intends to improve the home page (README) a bit, to provide better guidance in conveying what's inside, also visually more pleasant.
Any kinds of suggestions are welcome. Thank you.
See [README](https://github.com/crate/cratedb-examples/blob/amo/readme-styled/README.md).

Documentation: Add a bit of style to the README

---

README.md

Build status badges for corresponding items, and more, will be on a dedicated page, so there is no need to maintain them at two different places.
This patch depends on that other one.
- https://github.com/crate/crate-clients-tools/pull/75

README: Refactor "Build Status" section to dedicated page

---

topic/machine-learning/llm-langchain/cratedb_rag_customer_support.ipynb
topic/machine-learning/llm-langchain/cratedb_rag_customer_support_langchain.ipynb
topic/machine-learning/llm-langchain/requirements.txt

This should temporarily fix #302 
```
The conflict is caused by:
The user requested crate[sqlalchemy]>=0.34
cratedb-toolkit 0.0.5 depends on crate[sqlalchemy]>=0.34
langchain[cratedb,openai] 0.1.4 depends on crate[sqlalchemy]<0.35.0 and >=0.34.0; extra == "cratedb"
```

Set crate-python version to fixed to handle langchain requirement

---

.github/workflows/testing-native-python.yml
testing/native/python-pytest/requirements.txt
testing/native/python-unittest/requirements.txt

The "native" tests do not succeed on Python 3.12 yet, cr8 needs a corresponding fix.
```python
File "/path/to/cratedb-examples/testing/native/python-unittest/test_unittest.py", line 12, in <module>
from cr8.run_crate import create_node
File "/path/to/cratedb-examples/.venv312/lib/python3.12/site-packages/cr8/__init__.py", line 1, in <module>
import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

CI: Use Python 3.12 for exercising native Python test layers

---

application/apache-superset/conftest.py

It is hard to debug GH-313 when not being able to observe any stderr output from the child process.

Chore: Make subprocess.check_call not suppress its output

---

.github/workflows/application-apache-superset.yml
application/apache-superset/requirements.txt

Apache Superset 2.x is no longer actively supported. This patch removes testing on CI.
- GH-313
- https://github.com/apache/superset/discussions/27211

Apache Superset: Remove testing of Apache Superset 2.x

---

topic/machine-learning/automl/requirements.txt
topic/machine-learning/mlops-mlflow/requirements.txt

What the title says.
- https://github.com/crate-workbench/mlflow-cratedb/releases/tag/v2.10.2
/cc @andnig, @ckurze

ML: Update to mlflow-cratedb 2.10.2

---

topic/autoscaling/README.md

For GH-333 by @wierdvanderhaar, this patch actually uses Markdown for the README.md file (it used reStructuredText before), and applies some additional copy-edits on wording. We hope you appreciate the update.
The PR is targeted to towards your feature branch, `autoscale-example`, and can be merged into it as you like.

Chore: Copy-edit README about autoscaling

---

topic/autoscaling/autoscale.py

Just some Python code style nit wrt. GH-333.
For making `autoscale.py` a real program, and good Python citizen, it is
important to consider your file might be considered as a module, and
_imported_. In this case, you don't want to have your main code executed.
https://docs.python.org/3/library/__main__.html
In this case, the program would have caused any sort of test runner,
which scans directory trees for functions to executed, by, well,
importing all modules, to eventually run into an eternal loop.
When putting code into the top-level code environment, as exercised on
behalf of the `__name__ == '__main__'` code guard, it will safely
execute as a Python program, but not when used as a Python module.
In this spirit, a Python file can be both a program and a module at the
same time.
Other …

Autoscaling: Refactor code to top-level code environment, and format using `isort`

---

topic/machine-learning/automl/requirements.txt

Google Colab currently fails running `pip install`. `pycaret[analysis]` pulls in `pyyaml==5.3.1` (from 2020!), which no longer installs on Google Colab:
```
Collecting pyyaml==5.3.1 (from pycaret[analysis,models,parallel,test,tuner]==3.3.0->-r https://raw.githubusercontent.com/crate/cratedb-examples/main/topic/machine-learning/automl/requirements.txt (line 5))
Using cached PyYAML-5.3.1.tar.gz (269 kB)
error: subprocess-exited-with-error
× python setup.py egg_info did not run successfully.
│ exit code: 1
╰─> See above for output.
note: This error originates from a subprocess, and is likely not a problem with pip.
Preparing metadata (setup.py) ... error
error: metadata-generation-failed
× Encountered error while generating package metadata.
╰─> See above for output.
```
I couldn't find any …

Fix dependency installation for `topic/machine-learning/automl`

---

application/apache-kafka-flink/.env

A patch by @matriv is apparently part of Flink 1.18 now.
- https://github.com/apache/flink-connector-jdbc/pull/29
Accompanying the release of [cratedb-flink-jobs-0.5](https://github.com/crate/cratedb-flink-jobs/releases/tag/0.5), which includes the update to Flink 1.18, this patch verifies it on CI.
/cc @surister

Apache Kafka+Flink: Update to cratedb-flink-jobs-0.5, using Flink 1.18

---

topic/timeseries/dask-weather-data-import.ipynb
topic/timeseries/test.py

Make it more convenient to go data shopping using the CrateDB/Dask notebook.
There are concerns about downloading and processing 200 MB worth of data again and again, so this patch may need a resource saver.
- https://github.com/crate-workbench/cratedb-toolkit/issues/89
- GH-350
- https://github.com/crate-workbench/cratedb-toolkit/pull/124

Time Series QA: Make Dask notebook self-contained and testable 

---

topic/machine-learning/llm-langchain/test.py

Authenticating against Vertex AI is apparently more complicated, and currently, CI/GHA does not have corresponding credentials.
Just skip the corresponding examples on CI.

ML/LLM/RAG: Skip Vertex AI examples on CI

---

.github/workflows/ml-automl.yml
topic/machine-learning/automl/requirements.txt
topic/machine-learning/mlops-mlflow/requirements.txt
topic/timeseries/requirements.txt

- Python 3.11.9 breaks previous Dask.
- TSML: Use Python 3.11 again, reverting ea3bc2409 from GH-401.

TSML: Update to dask 2024.4.1 and mlflow-cratedb 2.11.3

---

.github/workflows/timeseries.yml
by-dataframe/dask/requirements.txt
topic/machine-learning/automl/requirements.txt
topic/timeseries/requirements.txt

This patch fixes a few dependency issues, where we needed to add extra version constraints last week, to untrip the situation. With the release of PyCaret 3.3.1, the situation becomes more relaxed again.
- https://github.com/pycaret/pycaret/issues/3966
/cc @marijaselakovic, @ckurze

TSML: Adjust dependencies around PyCaret/Joblib and Dask

---

topic/machine-learning/llm-langchain/cratedb_rag_customer_support_langchain.ipynb

1. There was a closing double quote around the URL at `pip install`, but no opening one
2. Colab was not able to resolve dependencies within 30 minutes. Removing optional, but unused, `pueblo` dependencies fixed it.

Fix the `cratedb_rag_customer_support_langchain.ipynb` notebook

---

.github/workflows/dataframe-dask.yml
.github/workflows/dataframe-pandas.yml
.github/workflows/ml-automl.yml
.github/workflows/ml-langchain.yml
.github/workflows/ml-mlflow.yml
.github/workflows/timeseries.yml
topic/machine-learning/automl/pyproject.toml
topic/machine-learning/automl/requirements.txt
topic/machine-learning/automl/test.py
topic/machine-learning/llm-langchain/conftest.py
topic/machine-learning/llm-langchain/pyproject.toml
topic/machine-learning/llm-langchain/requirements.txt
topic/machine-learning/llm-langchain/test.py
topic/machine-learning/mlops-mlflow/pyproject.toml
topic/machine-learning/mlops-mlflow/requirements.txt
topic/machine-learning/mlops-mlflow/test.py
topic/timeseries/conftest.py
topic/timeseries/exploratory_data_analysis.ipynb
topic/timeseries/time-series-decomposition.ipynb
topic/timeseries/timeseries-anomaly-detection.ipynb

The `topic/timeseries` slot already started using the `testbook` package for testing. This patch also makes the other notebook testing code in `topic/machine-learning` use [testbook](https://pypi.org/project/testbook/) instead of [pytest-notebook](https://pypi.org/project/pytest_notebook/), what has been used before.

ML: Use `testbook` instead of `pytest-notebook`

---

topic/timeseries/README.md
topic/timeseries/dask-weather-data-import.ipynb

- Finalization in wording
- Finalization in dependencies, tested on Google Colab.

Finalization of Dask Batch Import Notebook

---

by-language/javascript-typeorm/src/controller/UserController.ts
by-language/javascript-typeorm/src/entity/User.ts

Adjust example about that primary autogenerated keys with CrateDB are UUIDs, stored as strings.
This example uses those other dialect patches needed to make TypeORM compatible with CrateDB.
- https://github.com/crate-workbench/typeorm/pull/1
- https://github.com/crate-workbench/typeorm/pull/2
It is also stacked upon this one.
- GH-187

TypeORM: ID column to string to support UUID

---

.github/workflows/lang-npgsql.yml

Npgsql v8.0.3 has been released last week.
https://github.com/npgsql/npgsql/releases/tag/v8.0.3
- Supersedes GH-451.

Chore: Update CI to use Npgsql 6.0.11, 7.0.7, and 8.0.3

---

topic/machine-learning/llm-langchain/cratedb-vectorstore-rag-openai-sql.ipynb

In the original code you get the following warning:
LangChainDeprecationWarning: The class `langchain_community.embeddings.openai.OpenAIEmbeddings` was deprecated in langchain-community 0.1.0 and will be removed in 0.2.0. 
An updated version of the class exists in the langchain-openai package and should be used instead. 
To use it run `pip install -U langchain-openai` and import as `from langchain_openai import OpenAIEmbeddings`.

Chore: Fix LangChain import warning

---

application/apache-superset/requirements.txt
by-dataframe/dask/README.md
by-dataframe/dask/insert_dask.py
by-dataframe/dask/requirements.txt
by-dataframe/pandas/README.md
by-dataframe/pandas/insert_pandas.py
by-dataframe/pandas/requirements.txt
by-dataframe/polars/read_sqlalchemy.py
by-dataframe/polars/write_sqlalchemy.py
by-language/python-sqlalchemy/insert_efficient.py
topic/machine-learning/automl/requirements.txt
topic/machine-learning/llm-langchain/requirements.txt
topic/machine-learning/mlops-mlflow/requirements.txt
topic/timeseries/dask-weather-data-import.ipynb
topic/timeseries/requirements.txt
topic/timeseries/timeseries-queries-and-visualization.ipynb

The [CrateDB SQLAlchemy dialect](https://github.com/crate-workbench/sqlalchemy-cratedb) needs more love, so it was separated from the [DBAPI HTTP driver](https://github.com/crate/crate-python). This patch verifies and concludes the migration.
- https://github.com/crate/roadmap/issues/85
/cc @karynzv, @hlcianfagna, @wierdvanderhaar, @matriv, @seut

Dependencies: Migrate from `crate[sqlalchemy]` to `sqlalchemy-cratedb`

---

topic/machine-learning/automl/README.md
topic/machine-learning/automl/automl_classification_with_pycaret.ipynb
topic/machine-learning/automl/automl_timeseries_forecasting_with_pycaret.ipynb
topic/machine-learning/llm-langchain/README.md
topic/machine-learning/llm-langchain/conversational_memory.ipynb
topic/machine-learning/llm-langchain/conversational_memory.py
topic/machine-learning/llm-langchain/cratedb-vectorstore-rag-openai-sql.ipynb
topic/machine-learning/llm-langchain/cratedb_rag_customer_support.ipynb
topic/machine-learning/llm-langchain/cratedb_rag_customer_support_langchain.ipynb
topic/machine-learning/llm-langchain/cratedb_rag_customer_support_vertexai.ipynb
topic/machine-learning/llm-langchain/document_loader.ipynb
topic/machine-learning/llm-langchain/document_loader.py
topic/machine-learning/llm-langchain/vector_search.ipynb
topic/machine-learning/llm-langchain/vector_search.py
topic/machine-learning/mlops-mlflow/README.md
topic/timeseries/README.md
topic/timeseries/dask-weather-data-import.ipynb
topic/timeseries/exploratory_data_analysis.ipynb
topic/timeseries/time-series-decomposition.ipynb
topic/timeseries/timeseries-anomaly-detection.ipynb
topic/timeseries/timeseries-queries-and-visualization.ipynb

Diverging sets of dependencies are a constant struggle for people vs.
machines, either aiming to use the notebooks, or to validate them,
respectively.
The idea is to improve the situation by referring to the canonical
`requirements.txt` file from everywhere. In this spirit, dependency
updates can be driven well by Dependabot, and relevant software
artefacts should be synchronized better.
- By using absolute URLs to the `requirements.txt` files, the relevant `pip install` invocation should also work well on runtime environments like Google Colab, which need them.
- By using the `--upgrade` / `-U` option for `pip install`, let's try to ensure dependencies are always up-to-date.

Synchronize dependencies by using `requirements.txt` across the board

---

.github/dependabot.yml

Intending to improve the situation with recent dependency havocs.
For more volatile packages, this will increase churn. For all others, and in general, it will report sad dependency situations earlier than before.
- GH-484
- GH-483

CI: Let Dependabot probe dependency updates on a daily basis

---

topic/timeseries/dask-weather-data-import.ipynb
topic/timeseries/requirements.txt
topic/timeseries/test.py

For the time series notebooks, update pandas and SQLAlchemy to use more recent versions.
An alternative to GH-400, where anyone can collaborate on the same branch. This makes sense if it is a long running one, because, for example, when it needs contributions from more people while we go.
- GH-379
- GH-383
- GH-477
- GH-476

Time Series: Update to pandas 2.0 and SQLAlchemy 2.0

---

topic/machine-learning/automl/requirements-dev.txt
topic/machine-learning/automl/requirements.txt
topic/machine-learning/mlops-mlflow/requirements-dev.txt
topic/machine-learning/mlops-mlflow/requirements.txt

[mlflow-cratedb 2.14.0](https://github.com/crate/mlflow-cratedb/releases/tag/v2.14.0) has been released. See release notes for [MLflow 2.14.0](https://github.com/mlflow/mlflow/releases/tag/v2.14.0). This update pulls in that version, also updating to [cratedb-toolkit==0.0.14](https://github.com/crate-workbench/cratedb-toolkit/releases/tag/v0.0.14).

ML: Update to MLflow 2.14

---

topic/timeseries/exploratory_data_analysis.ipynb
topic/timeseries/test.py
topic/timeseries/time-series-decomposition.ipynb

Accompany and complete:
- GH-430
Conclude and finalize fixes:
- GH-387
- GH-478
- GH-493
> `groupby.mean()` has `numeric_only=` argument whose default value was `True` in the past but since pandas 2.0, its default value is `False`.
>
> An implication is that string columns are not dropped when a statistical method such as `mean` or `std` is called on the `groupby` object (as was done in the past). To solve the issue, pass `numeric_only=True`.
>
> -- https://stackoverflow.com/a/76597931

Time Series: More compatibility with pandas 2.0

---

.github/workflows/lang-php-amphp.yml
by-language/php-amphp/basic.php
by-language/php-amphp/composer.json
by-language/php-amphp/composer.lock

- Updates to amphp/amp 3.x. -- https://amphp.org/amp
- Includes and extends GH-487.
- Remove support for PHP 7. Add support for PHP 8.3.

PHP/AMPHP: Update to amphp/amp v3 by switching to `Revolt\EventLoop`

---

topic/machine-learning/automl/requirements.txt
topic/machine-learning/mlops-mlflow/requirements.txt

Update dependencies to use MLflow 2.14.1, released 5 days ago.
-- https://github.com/crate/mlflow-cratedb/releases/tag/v2.14.1

Dependencies: Update to mlflow-cratedb 2.14.1

---

.github/dependabot.yml
.github/workflows/framework-gradio.yml
framework/gradio/.gitignore
framework/gradio/README.md
framework/gradio/basic_sys_summits.py
framework/gradio/pyproject.toml
framework/gradio/requirements-dev.txt
framework/gradio/requirements.txt
framework/gradio/test.py

Coming from GH-506, this patch will verify basic connectivity with Gradio works.
- https://github.com/crate/crate-clients-tools/issues/131

Framework/Gradio: Add basic example about Gradio, reading `sys.summits`

---

application/apache-kafka-flink-streaming/README.md

docker-compose is a separate executable nowadays.  
The ingest from Flink fails when you use the old create table statement because only location and current are ingested. With these generated columns, we are sure that the ingests are successful.

Kafka/Flink: Fix DDL statement

---

.github/workflows/testing-native-python.yml
.github/workflows/testing-testcontainers-python.yml

Because `cratedb-sqlparse` is now part of `cratedb-toolkit`, it only supports Python 3.8 and higher now.
- GH-516
- GH-517

Testing: Drop support for Python 3.7

---

application/cratedb-toolkit/requirements.txt
application/cratedb-toolkit/test_io.py

Validate CTK's InfluxDB Table Loader by importing ILP data from https://github.com/influxdata/influxdb2-sample-data/tree/master/air-sensor-data.
- https://github.com/daq-tools/influxio/pull/142

CTK: Validate InfluxDB Table Loader

---

application/cratedb-toolkit/requirements.txt
application/cratedb-toolkit/test_io.py
application/cratedb-toolkit/zyp-mongodb-json-files.yaml

On a specific collection loaded from a MongoDB Extended JSON file, mask (exclude/ignore/omit) certain elements, in order to import all records without further errors.
Both elements will be dropped:
- `.image.available_sizes`
- `.screenshots[].available_sizes`
The procedure can be improved on a later iteration.
- https://github.com/crate/commons-codec/pull/49
- https://github.com/crate/commons-codec/pull/50
- https://github.com/crate/cratedb-toolkit/pull/269
/cc @juanpardo, @wierdvanderhaar, @hlcianfagna, @ckurze

CTK: Invoke MongoDB Table Loader with Zyp Transformation

---

testing/native/python-pytest/test_pytest.py

`pytest-crate` was no longer maintained. `pytest-cratedb` became the canonical package now.

Testing: Update test_pytest.py example re. `pytest-cratedb` name

---

application/cratedb-toolkit/requirements.txt
application/cratedb-toolkit/test_io.py
application/cratedb-toolkit/zyp-mongodb-json-files.yaml

A few more transformations for importing collections from https://github.com/ozlerhakan/mongodb-json-files into CrateDB tables, after the very first variant used the Polars loader that obviously stripped away all the nested elements. 
Now, the anomalies that would otherwise make it impossible to import data into CrateDB 1:1, are handled by corresponding [jqlang expressions](https://jqlang.github.io/jq/manual/), partially just omitting offending data, but mostly converting its shape to a canonical representation.
- GH-645
- GH-677
/cc @hlcianfagna, @wierdvanderhaar, @zolbatar, @kneth, @surister

Table Loader: Update to CTK 0.0.29

---

.github/workflows/lang-npgsql.yml
by-language/csharp-npgsql/README.rst
by-language/csharp-npgsql/demo.csproj

- Remove support for .NET 6 and Npgsql 6.
- Add support for .NET 9.
- Update CI to use Npgsql versions 7.0.8 and 8.0.5.
- GH-675

Npgsql: Adjust .NET support and version numbers on CI

---

.github/workflows/ml-langchain.yml

Verify if the LangChain stack (both library and examples) works well on Python 3.13 already.
It does not work, yet. pyarrow 18 will be needed.
```
Building wheel for pyarrow (pyproject.toml) did not run successfully.
```
-- https://github.com/crate/cratedb-examples/actions/runs/11512456606/job/32047504093?pr=699#step:6:853
Edit: [pyarrow 18](https://pypi.org/project/pyarrow/18.0.0/) has been released on Oct, 28.

ML/LangChain: Verify examples on Python 3.13

---

application/apache-superset/requirements.txt

Trying to fix CI for Apache Superset.
- GH-741

Apache Superset: Downgrade to PyJWT 2.9

---

.github/workflows/application-apache-superset.yml
application/apache-superset/superset_config.py
application/apache-superset/test.py

Apache Superset 4 was released on Apr 8, 2024.
-- https://pypi.org/project/apache-superset/#history

Apache Superset: Add version 4 to test matrix

---

by-language/java-jdbc/Makefile
by-language/java-jdbc/README.rst
by-language/java-qa/src/test/java/io/crate/qa/JdbcMetaDataTest.java
by-language/java-qa/src/test/java/io/crate/qa/JdbcTest.java

Otherwise, resources would be created within the `crate` schema, which might be unfortunate for various reasons.
The intention of the micro examples is to show users best practices. While the documentation will certainly educate about the `doc` schema, I think it will be fine to use a canonical dedicated schema name for this collection of example programs?
- See also: https://github.com/crate/crate-clients-tools/pull/151

Java JDBC: Use explicit schema name `testdrive`

---

application/apache-superset/requirements.txt
application/apache-superset/superset_config.py

There was a policy/constraint update in PyJWT 2.10 that broke the little test harness.
- https://github.com/jpadilla/pyjwt/issues/1017
[flask-jwt-extended 4.7.1](https://github.com/vimalloc/flask-jwt-extended/releases/tag/4.7.1) compensates for that, by also configuring `JWT_VERIFY_SUB = False`.
- https://github.com/crate/cratedb-examples/issues/741
- https://github.com/apache/superset/issues/30995
- https://github.com/dpgaspar/Flask-AppBuilder/issues/2287

Apache Superset: Fix JWT problem by updating to flask-jwt-extended 4.7.1

---

.github/dependabot.yml
.github/workflows/application-metabase.yml
application/metabase/README.md
application/metabase/backlog.md
application/metabase/docker-compose.yml
application/metabase/metabase_rig.py
application/metabase/pyproject.toml
application/metabase/requirements-test.txt
application/metabase/requirements.txt
application/metabase/test.py

A basic test case that reads CrateDB's `sys.summit` table through Metabase, after connecting CrateDB as a PostgreSQL database.
In order to prove it worked in general, this recipe uses Metabase v0.48.3, while it will start failing with v0.48.4.
- https://github.com/crate/crate-clients-tools/issues/153

Metabase: Add test harness for validating Metabase against CrateDB

---

by-language/csharp-npgsql/DemoTypes.cs
by-language/csharp-npgsql/tests/DemoProgramTest.cs

Newer .NET/C# language versions borrow from Python for defining multi-line strings, using `""" Hello, world. """`. This is much better for inlining JSON documents, because it doesn't need additional quoting.

Npgsql: Use improved .NET multi-line strings

---

.github/workflows/lang-npgsql.yml
by-language/csharp-npgsql/demo.csproj

Use `<TargetFramework>net$(NETCoreAppMaximumVersion)</TargetFramework>` in `.csproj` to set the target framework to the latest version available for the SDK. Thanks, @meziantou!
-- https://www.meziantou.net/how-to-use-the-latest-target-framework-available-for-a-dotnet-sdk.htm
/cc @simonprickett, @kneth

Npgsql: Use the latest .NET target framework available

---

by-language/csharp-npgsql/BasicPoco.cs
by-language/csharp-npgsql/DemoProgram.cs
by-language/csharp-npgsql/DemoTypes.cs
by-language/csharp-npgsql/README.rst
by-language/csharp-npgsql/tests/DemoProgramTest.cs

This patch resolves a few FIXME admonitions introduced by a recent patch that started to validate all of CrateDB's data types with Npgsql.
- Yay: GH-772
- Not applicable: GH-776
Vanilla Npgsql provides good enough support to handle CrateDB's ARRAY and OBJECT types better than just plain strings. This patch demonstrates type mappings using three different variants:
- Native .NET `System.Collections.Generic.List` and `System.Collections.Generic.Dictionary` types.
- Native .NET `System.Text.Json.JsonDocument` type. [^1] Thanks, @simonprickett.
- Custom .NET POCO types.
- Use `NpgsqlDbType.Json` explicitly where applicable, for example when communicating parameters using `AddWithValue()`.
- Use `EnableDynamicJson()` on the `NpgsqlDataSourceBuilder`, for POCO and `Dictionary` mappings that …

Npgsql: Use `EnableDynamicJson` to unlock better container type mappings

---

.github/workflows/lang-python-dbapi.yml

CI: Provide Python 3.7. EOL, it was removed from recent GHA runners

---

.github/dependabot.yml
.github/workflows/framework-dbt.yml
framework/dbt/basic/README.md
framework/dbt/basic/dbt_project.yml
framework/dbt/materialize/.gitignore
framework/dbt/materialize/README.md
framework/dbt/materialize/dbt_project.yml
framework/dbt/materialize/models/example/jobslog.sql
framework/dbt/materialize/models/example/test.sql
framework/dbt/materialize/packages.yml
framework/dbt/materialize/profiles.yml
framework/dbt/materialize/requirements.txt
framework/dbt/materialize/tests/test.yml

Add example for dbt, exercising incremental materialization using the `delete+insert` strategy, as suggested by @hlcianfagna per https://github.com/crate/dbt-cratedb2/issues/7#issuecomment-2536580424. Thanks!
- https://github.com/crate/dbt-cratedb2/issues/10

dbt: Example project using `delete+insert` materialization

---

application/cratedb-toolkit/requirements.txt
application/cratedb-toolkit/test_io.py

Data from InfluxDB Line Protocol format can be loaded directly into CrateDB using the CrateDB Toolkit.
- https://github.com/crate/cratedb-toolkit/pull/333
- https://github.com/crate/cratedb-guide/pull/170
/cc @wierdvanderhaar, @simonprickett, @kneth

CTK/InfluxDB: Demonstrate loading ILP data

---

.github/workflows/application-cratedb-toolkit.yml
.github/workflows/lang-python-sqlalchemy.yml
.github/workflows/testing-native-python.yml
.github/workflows/testing-testcontainers-python.yml
application/apache-superset/requirements.txt
application/cratedb-toolkit/requirements.txt
application/records/requirements.txt
by-dataframe/dask/requirements.txt
by-dataframe/pandas/requirements.txt
by-language/python-dbapi/requirements.txt
by-language/python-sqlalchemy/requirements.txt
framework/flink/kafka-jdbcsink-python/requirements.txt
framework/gradio/requirements.txt
framework/records/requirements.txt
framework/streamlit/requirements.txt
testing/native/python-pytest/requirements.txt
testing/native/python-unittest/requirements.txt
testing/testcontainers/python-pytest/requirements.txt
testing/testcontainers/python-unittest/requirements.txt
topic/machine-learning/automl/requirements.txt
topic/timeseries/requirements.txt

Validate and bring in an improvement to crate-python.
- https://github.com/crate/crate-python/pull/691
- https://github.com/crate/crash/pull/459
- https://github.com/crate/cratedb-toolkit/pull/349
- https://github.com/crate/sqlalchemy-cratedb/pull/195
- https://github.com/crate/langchain-cratedb/pull/23
/cc @seut, @simonprickett, @hlcianfagna, @wierdvanderhaar

Update to `crate-2.0.0`, which uses `orjson` for JSON marshalling

---

by-dataframe/sqlframe/example_types.py

When submitting a record like this to CrateDB using [SQLFrame](https://github.com/eakmanrq/sqlframe),
https://github.com/crate/cratedb-examples/blob/82cb58159d3371ba2a48f374da9245faf9784e3f/by-dataframe/sqlframe/example_types.py#L41-L61
... it generates SQL statements like this:
```sql
SELECT 
...
"integer" AS "integer", 
"bigint" AS "bigint",
"float" AS "float", 
...
```
With an aliasing to `char`, changed within this patch (instead of `character`), CrateDB only trips on the `"char" AS "char"` fragment, but not on others.
```python
psycopg2.errors.InternalError_: line 1:229: no viable alternative at input
```
```sql
SELECT 
"bool" AS "bool", 
"text" AS "text", 
"char" AS'
```
```sql
cr> select 42 as "string";
+---------+
| string |
+---------+
|      42 |
+---------+
SELECT 1 row in set …
```

SQLFrame: On the "all-types" validation, use `char` instead of `character`

---

application/apache-superset/requirements.txt
application/cratedb-toolkit/requirements.txt
application/records/requirements.txt
by-dataframe/dask/requirements.txt
by-dataframe/pandas/requirements.txt
by-language/python-dbapi/requirements.txt
by-language/python-sqlalchemy/requirements.txt
framework/flink/kafka-jdbcsink-python/requirements.txt
framework/gradio/requirements.txt
framework/records/requirements.txt
framework/streamlit/requirements.txt
testing/native/python-pytest/requirements.txt
testing/native/python-unittest/requirements.txt
testing/testcontainers/python-pytest/requirements.txt
testing/testcontainers/python-unittest/requirements.txt
topic/machine-learning/automl/requirements.txt
topic/timeseries/requirements.txt

The fundamental patch GH-811 needs a little update, pulling in a more recent pre-release version of crate-python.
- https://github.com/crate/crate-python/pull/691

Dependencies: Update to `crate>=2.0.0.dev6`, restoring JSON marshalling

---

.github/workflows/lang-npgsql.yml

Remove testing on .NET 8.x, as it stopped working on CI/GHA two weeks ago. Is it legit?
Error: /usr/share/dotnet/sdk/9.0.102/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(266,5):
error NETSDK1005: Assets file '/home/runner/work/cratedb-examples/cratedb-examples/by-language/csharp-npgsql/obj/project.assets.json' doesn't have a target for 'net8.0'. Ensure that restore has run and that you have included 'net8.0' in the TargetFrameworks for your project. [/home/runner/work/cratedb-examples/cratedb-examples/by-language/csharp-npgsql/demo.csproj]
- https://github.com/crate/cratedb-examples/actions/runs/13044843111/job/36393610035#step:7:77

Npgsql: Remove testing on .NET 8.x

---

.github/dependabot.yml
.github/workflows/lang-rust-postgres.yml
by-language/rust-postgres/.gitignore
by-language/rust-postgres/Cargo.toml
by-language/rust-postgres/README.md
by-language/rust-postgres/src/main.rs
by-language/rust-postgres/src/tests.rs

Add minimal Rust example from [crate-qa](https://github.com/crate/crate-qa/tree/master/tests/client_tests/rust) to make a start, adding a miniature rig for further explorations.
/cc @kneth

Rust: Add minimal example

---

.github/dependabot.yml

On the [Dependabot job overview page](https://github.com/crate/cratedb-examples/network/updates), we discovered a few jobs that failed.

CI: Fix Dependabot configuration, a few paths were wrong

---

framework/mcp/example_builtin.py
framework/mcp/example_dbhub.py
framework/mcp/test.py

A recent update to [@bytebase/dbhub](https://www.npmjs.com/package/@bytebase/dbhub) made our [integration tests go south](https://github.com/crate/cratedb-examples/actions/workflows/framework-mcp.yml), because we didn't employ any version pinning there up until now.
- https://github.com/quarkiverse/quarkus-mcp-servers/issues/30

MCP: Employ version pinning for MCP server components

---

.github/workflows/framework-mcp.yml
framework/mcp/README.md
framework/mcp/example_builtin.py
framework/mcp/example_dbhub.py
framework/mcp/example_jdbc.py
framework/mcp/example_mcp_alchemy.py
framework/mcp/requirements.txt
framework/mcp/test.py

- A little follow-up to https://github.com/crate/cratedb-examples/pull/853.
- This snippet uses [MCP Alchemy](https://github.com/runekaagaard/mcp-alchemy), which in turn can use the [CrateDB dialect](https://cratedb.com/docs/sqlalchemy-cratedb/) ~~without much ado~~ when including the patch referenced below, now also included into the pre-release [0.42.0.dev1](https://pypi.org/project/sqlalchemy-cratedb/0.42.0.dev1/).
- https://github.com/crate/sqlalchemy-cratedb/pull/217

MCP: Add example about MCP Alchemy

---

.github/workflows/framework-mcp.yml
framework/mcp/.gitignore
framework/mcp/README.md
framework/mcp/backlog.md
framework/mcp/example_pg_mcp.py
framework/mcp/example_pg_mcp_install.sh
framework/mcp/example_pg_mcp_server.py
framework/mcp/mcp_utils.py
framework/mcp/test.py

- A little follow-up to GH-853, similar like GH-880.
- This snippet uses [PG-MCP](https://github.com/stuzero/pg-mcp), which in turn can use CrateDB with the patch referenced below.
- https://github.com/crate-workbench/pg-mcp/pull/1

MCP: Add example about PG-MCP

---

framework/mcp/README.md
framework/mcp/backlog.md
framework/mcp/example_cratedb_mcp.py
framework/mcp/requirements.txt
framework/mcp/test.py

This snippet uses the [CrateDB MCP Server](https://github.com/crate/cratedb-mcp), which specialises on advanced CrateDB operations.
- https://github.com/crate/cratedb-mcp/pull/3

MCP: Add example about CrateDB MCP

---

framework/mcp/requirements.txt

Accompanying recent adjustments to the package setup of `cratedb-mcp`.
- https://github.com/crate/cratedb-mcp/pull/3

MCP: Use `cratedb-mcp@main`

---

application/cratedb-toolkit/requirements.txt
application/cratedb-toolkit/test_io.py
framework/mcp/README.md
framework/mcp/requirements.txt
testing/testcontainers/python-pytest/requirements.txt
testing/testcontainers/python-unittest/requirements.txt
topic/machine-learning/automl/requirements-dev.txt
topic/machine-learning/llama-index/requirements-dev.txt
topic/machine-learning/llm-langchain/requirements-dev.txt
topic/machine-learning/mlops-mlflow/requirements-dev.txt
topic/timeseries/requirements.txt

Renamed CLI option `--cratedb-sqlalchemy-url` to `--cluster-url`
and environment variable `CRATEDB_SQLALCHEMY_URL` to `CRATEDB_CLUSTER_URL`.

Dependencies: Update to cratedb-toolkit 0.0.33

---

.github/workflows/ml-langchain.yml
topic/machine-learning/llm-langchain/.gitignore
topic/machine-learning/llm-langchain/README.md
topic/machine-learning/llm-langchain/agent_with_mcp.py
topic/machine-learning/llm-langchain/init.sql
topic/machine-learning/llm-langchain/requirements.txt
topic/machine-learning/llm-langchain/test.py

For Text-to-SQL purposes, exercise the [langchain-mcp-adapters](https://pypi.org/project/langchain-mcp-adapters/) package together with the [CrateDB MCP Server](https://cratedb.com/docs/guide/integrate/mcp/cratedb-mcp.html), also to validate its OCI standard image published to GHCR.
- https://github.com/crate/cratedb-examples/pull/1032

LangChain: Add example using MCP

---

topic/machine-learning/llama-index/boot.py
topic/machine-learning/llama-index/demo_nlsql.py
topic/machine-learning/llama-index/env.azure
topic/machine-learning/llama-index/env.standalone
topic/machine-learning/llama-index/requirements.txt
topic/machine-learning/llama-index/test.py

- [`gemma3:1b`](https://ollama.com/library/gemma3) looks very promising when used with LlamaIndex' `NLSQLTableQueryEngine`. Validated with a basic Text-to-SQL job, it responds in approx. 8 seconds on a lousy CPU, while OpenAI GPT-4.1 via SaaS also takes up to 5 seconds.
- Don't explicitly specify table names `NLSQLTableQueryEngine` for generic use cases.

LlamaIndex: Evaluate Ollama LLM backend with smaller models

---

topic/machine-learning/llama-index/README.md
topic/machine-learning/llama-index/boot.py
topic/machine-learning/llama-index/demo_nlsql.py
topic/machine-learning/llama-index/env.standalone
topic/machine-learning/llm/requirements.txt
topic/machine-learning/llm/sql-request.txt
topic/machine-learning/llm/sql-response.txt
topic/machine-learning/llm/test.xsh

It looks like `gemma3:1b` can do Text-to-SQL reasonably, at least on basic inquiries, when using good instructions, in this case from LlamaIndex, coming from LangChain.

LlamaIndex and `llm`: Evaluate `gemma3:1b` with Ollama
