crate/cratedb-examples

spikes/testbench-yellowcab/README.rst
spikes/testbench-yellowcab/cratedb-import-nyc-yellowcab.sh

Supporting https://github.com/crate/cloud-ui/pull/1474.

Add example about importing the NYC Yellowcab data set

---

.github/workflows/tests-npgsql.yml
by-language/csharp-npgsql/README.rst
by-language/csharp-npgsql/demo.csproj

csharp-npgsql: Update to Npgsql 6.0.8 for compat. with CrateDB>=4.8.4

---

.github/workflows/tests-npgsql.yml
by-language/csharp-npgsql/README.rst
by-language/csharp-npgsql/demo.csproj

Another modernization patch to update the `csharp-npgsql` project.

CI: Update `csharp-npgsql` to CrateDB 5.2.0, .NET 5, 6, and 7, and Npgsql 6 and 7

---

stacks/kafka-flink/.gitignore
stacks/kafka-flink/README.Unix.rst
stacks/kafka-flink/README.Windows.rst
stacks/kafka-flink/README.rst
stacks/kafka-flink/backlog.rst
stacks/kafka-flink/docker-compose.yml

Just a small update to some bits of the corresponding documentation about the Kafka/Flink/CrateDB pipeline scenario.

Kafka/Flink: Improve documentation

---

.github/dependabot.yml

Chore: Add Dependabot configuration file

---

by-language/java-jooq/build.gradle

This bundles a few individual PRs submitted by Dependabot.

Java/jOOQ: Update dependencies

---

.github/workflows/test-npgsql.yml
by-language/csharp-npgsql/demo.csproj

This bundles a few individual PRs submitted by Dependabot.

C#/Npgsql: Update dependencies

---

.github/workflows/test-java-jdbc.yml
by-language/java-jdbc/pom.xml

This adds a CI configuration and bundles a few individual PRs submitted by Dependabot.

Java/JDBC: Add CI configuration and update dependencies

---

.github/workflows/test-ruby.yml

This adds a CI configuration for the Ruby example.

Ruby: Add CI configuration

---

stacks/kafka-flink/.env
stacks/kafka-flink/README.rst

Merge once: https://github.com/crate/cratedb-flink-jobs/issues/15 is complete

Upgrade to Flink 1.17.0

---

by-language/csharp-npgsql/demo.csproj

C#/Npgsql: Update from .NET Framework 4.6 to 4.8

---

.github/workflows/test-java-jdbc.yml
.github/workflows/test-java-jooq.yml
.github/workflows/testcontainers-java.yml

Let's use this PR to update CI to use Java 21.

CI: Add Java 21

---

requirements.txt

Chore: Update to `pueblo==0.0.3`

---

topic/machine-learning/vectorstore/vector-store-rag-openai.ipynb

- New sample how to use CrateDB's vector store and similarity search with plain SQL.
CC: @marijaselakovic @amotl

ML: Added RAG pipeline with plain SQL usage for Vector Store

---

topic/machine-learning/classification-automl/README.md
topic/machine-learning/llm-langchain/cratedb-vectorstore-rag-openai.ipynb

ML: Fix more flaws

---

topic/machine-learning/automl/automl_timeseries_forecasting_with_pycaret.ipynb
topic/machine-learning/automl/pyproject.toml
topic/machine-learning/automl/requirements.txt

- diff_ignore
- nb_diff_ignore
- Downgrade to pydantic<2 to remove runtime warning

Fix testing of `automl_timeseries_forecasting_with_pycaret.ipynb`

---

topic/machine-learning/mlops-mlflow/tracking_merlion.ipynb
topic/machine-learning/mlops-mlflow/tracking_merlion.py

Chore: Link to `nab-machine-failure.csv` dataset changed

---

topic/machine-learning/automl/README.md
topic/machine-learning/automl/requirements-dev.txt
topic/machine-learning/llm-langchain/requirements-dev.txt
topic/machine-learning/llm-langchain/requirements.txt
topic/machine-learning/mlops-mlflow/requirements-dev.txt

ML: Dependencies and wording

---

.github/workflows/test-automl.yml

as the title suggests
- [`x] [CLA](https://crate.io/community/contribute/cla/) is signed

use python 3.11 for automl nightlies

---

topic/machine-learning/llm-langchain/document_loader.py
topic/machine-learning/llm-langchain/requirements-dev.txt
topic/machine-learning/llm-langchain/requirements.txt
topic/machine-learning/llm-langchain/test.py

This patch intends to fix the failing nightly builds.
- GH-158
- https://github.com/pyveci/pueblo/pull/34

ML: Fix builds in `llm-langchain` folder

---

topic/machine-learning/llm-langchain/cratedb_rag_customer_support.ipynb
topic/machine-learning/llm-langchain/pyproject.toml

A patch to make GH-215 run to completion, along with a few other adjustments.

ML/LLM: RAG example copy edits

---

by-language/java-jooq/build.gradle
testing/testcontainers/java/build.gradle

Bundles a few slf4j updates into a single PR.
- GH-222
- GH-224
- GH-225
- GH-226
/cc @surister

Java: Update slf4j

---

by-dataframe/polars/one_db_to_another.py
by-dataframe/polars/read_pg.py
by-dataframe/polars/read_sqlalchemy.py
by-dataframe/polars/write_adbc.py
by-dataframe/polars/write_sqlalchemy.py

Solves: https://github.com/crate/cratedb-examples/issues/228

Add examples on how to read/write data from CrateDB using Polars

---

topic/machine-learning/llm-langchain/requirements-dev.txt
topic/machine-learning/llm-langchain/requirements.txt

Adjust dependencies to reflect updates to [LangChain 0.1.1](https://github.com/langchain-ai/langchain/releases/tag/v0.1.1), [cratedb-toolkit 0.0.3](https://github.com/crate-workbench/cratedb-toolkit/releases/tag/v0.0.3), and [pueblo 0.0.6](https://github.com/pyveci/pueblo/releases/tag/v0.0.6).
- https://github.com/crate-workbench/langchain/pull/1

ML: Update to LangChain 0.1.1, cratedb-toolkit 0.0.3, and pueblo 0.0.6

---

topic/machine-learning/llm-langchain/cratedb_rag_customer_support.ipynb
topic/machine-learning/llm-langchain/cratedb_rag_customer_support_langchain.ipynb
topic/machine-learning/llm-langchain/requirements.txt

Support GH-215, to remove a patch from the notebook.

RAG example: Slight improvement

---

topic/machine-learning/llm-langchain/cratedb-vectorstore-rag-openai-sql.ipynb
topic/machine-learning/llm-langchain/requirements.txt
topic/timeseries/explore/timeseries-queries-and-visualization.ipynb

Google Colab failed to resolve dependencies, see #255.

Fix dependency installation on Google Colab for `cratedb-vectorstore-rag-openai-sql.ipynb`

---

by-language/python-sqlalchemy/requirements-dev.txt
topic/machine-learning/llm-langchain/document_loader.ipynb
topic/machine-learning/llm-langchain/document_loader.py

- Python/SQLAlchemy: Fix outdated dev dependency, now using vanilla pueblo
- LLM/LangChain: Improve data loading into `mlb_teams_2012` database table
- GH-258

Chore: Fix CI by applying dependency updates and using more robust data acquisition code

---

topic/machine-learning/automl/requirements-dev.txt
topic/machine-learning/llm-langchain/requirements-dev.txt
topic/machine-learning/llm-langchain/requirements.txt
topic/machine-learning/mlops-mlflow/requirements-dev.txt

https://github.com/pyveci/pueblo/releases/tag/v0.0.7

Chore: Update to pueblo 0.0.7

---

topic/machine-learning/llm-langchain/cratedb_rag_customer_support_langchain.ipynb

A few copy-edits to the recently added LLM/RAG example.

ML/RAG/Twitter: Update intro text. Clean up Python imports.

---

.github/workflows/ml-automl.yml

AutoML runs work best on day times, apparently.

AutoML: Reschedule to run on day times

---

framework/microsoft-ssis/README.md
framework/microsoft-ssis/ssis-cratedb-demo.sln
framework/microsoft-ssis/ssis-cratedb-demo/Package.dtsx
framework/microsoft-ssis/ssis-cratedb-demo/Project.params
framework/microsoft-ssis/ssis-cratedb-demo/cratedb.conmgr
framework/microsoft-ssis/ssis-cratedb-demo/ssis-cratedb-demo.database
framework/microsoft-ssis/ssis-cratedb-demo/ssis-cratedb-demo.dtproj
framework/microsoft-ssis/ssis-cratedb-demo/ssis-cratedb-demo.dtproj.user

This patch adds an example shared by @hlcianfagna, which demonstrates connectivity to CrateDB using [SSIS] and [psqlODBC - PostgreSQL ODBC driver]. Thanks!
- https://github.com/crate/crate-clients-tools/pull/62
[psqlODBC - PostgreSQL ODBC driver]: https://odbc.postgresql.org/
[SSIS]: https://en.wikipedia.org/wiki/SQL_Server_Integration_Services

SSIS/ODBC: Add example Data Flow Task

---

topic/timeseries/dask-weather-data-import.ipynb

Building upon GH-293, this patch adds a few copy-edits. GH-294 might have been closed prematurely.

Timeseries: Copy-edits for notebook using Dask for batch imports

---

topic/autoscaling/README.md
topic/autoscaling/autoscale.py

Replace hardcoded line numbers in README.md with the ability to pass parameters to the script (sensitive parameters are environment variables, others as regular command-line parameters).
Use `prometheus_client` to parse the return value of the /metrics endpoint.

Autoscaling: Allow passing parameters dynamically / Use Prometheus client

---

topic/autoscaling/README.md

Added the real link to the community post.

Autoscaling: Update README.md

---

.github/dependabot.yml
.github/workflows/timeseries.yml
topic/timeseries/README.md
topic/timeseries/conftest.py
topic/timeseries/exploratory_data_analysis.ipynb
topic/timeseries/pyproject.toml
topic/timeseries/requirements-dev.txt
topic/timeseries/requirements.txt
topic/timeseries/test.py
topic/timeseries/time-series-decomposition.ipynb
topic/timeseries/timeseries-queries-and-visualization.ipynb

- Add a CI configuration for GHA.
- Make notebooks self-contained, also adding DDL and DML statements.
Otherwise, people or QA jobs invoking individual notebooks, or in a different order, are having a hard time.
- Minor copy-edits.

Time Series QA: Add CI configuration

---

.github/workflows/application-apache-kafka-flink.yml
.github/workflows/application-apache-superset.yml
.github/workflows/dataframe-dask.yml
.github/workflows/dataframe-pandas.yml
.github/workflows/lang-java-jooq.yml
.github/workflows/lang-java-maven.yml
.github/workflows/lang-npgsql.yml
.github/workflows/lang-php-amphp.yml
.github/workflows/lang-php-pdo.yml
.github/workflows/lang-python-sqlalchemy.yml
.github/workflows/lang-ruby.yml
.github/workflows/ml-automl.yml
.github/workflows/ml-langchain.yml
.github/workflows/ml-mlflow.yml
.github/workflows/testing-native-python.yml
.github/workflows/testing-testcontainers-java.yml
.github/workflows/testing-testcontainers-python.yml
.github/workflows/timeseries.yml

Just saying `requirements.txt` caught all `requirements.txt` files in all subdirectories. This patch anchors them to the repository root folder.

CI: Fix GHA path filters

---

topic/machine-learning/llm-langchain/README.md
topic/machine-learning/llm-langchain/cratedb_rag_customer_support_vertexai.ipynb
topic/machine-learning/llm-langchain/requirements.txt
topic/machine-learning/llm-langchain/test.py

- This PR illustrates how to implement the RAG pipeline on the Vertex AI platform.
- It requires authentication on Google Cloud and the specification of the relevant PROJECT ID and LOCATION.
- Updated requirements.txt file to include necessary modules.

RAG implementation for customer support scenario using Vertex AI

---

application/apache-kafka-flink-streaming/README.md
application/apache-kafka-flink-streaming/docker-compose.yml
application/apache-kafka-flink-streaming/flink_consumer.py
application/apache-kafka-flink-streaming/weather_producer.py

- Add some more logging statements.
- Add healthcheck for zookeper.
- Add table creation to the README.md

Apache Kafka/Flink: Minor improvements

---

topic/timeseries/timeseries-anomaly-detection.ipynb

Minor changes and typo correction

Minor changes and typo correction

---

by-dataframe/dask/requirements.txt
by-dataframe/pandas/requirements.txt
topic/machine-learning/automl/requirements-dev.txt
topic/machine-learning/automl/requirements.txt
topic/machine-learning/llm-langchain/requirements-dev.txt
topic/machine-learning/llm-langchain/requirements.txt
topic/machine-learning/mlops-mlflow/requirements-dev.txt
topic/timeseries/requirements-dev.txt
topic/timeseries/requirements.txt

When refactoring, even diligently, things occasionally go south. Apologies.
- GH-478
- GH-480
- GH-481
Provide better protection against accidental havocs, by nailing packages with more volatility using exact version constraints.

Dependencies: Use fixed version constraints for more volatile packages

---

topic/timeseries/dask-weather-data-import.ipynb

This reverts commit f0746461ad985535ad618b3bd0cf407023c8b805.
It made the Notebook rendering on GitHub go south.

Revert "Chore: Update `dask-weather-data-import.ipynb`"

---

by-dataframe/dask/requirements.txt
by-dataframe/pandas/requirements.txt
topic/machine-learning/llm-langchain/requirements.txt
topic/timeseries/requirements.txt

This bundles a few Dependabot PRs.
- GH-501
- GH-502
- GH-504
- GH-505
- https://github.com/crate/mlflow-cratedb/pull/156
- https://github.com/crate-workbench/langchain/pull/27

Dependencies: Update to sqlalchemy-cratedb==0.38.0

---

.github/dependabot.yml
.github/workflows/application-cratedb-toolkit.yml
application/cratedb-toolkit/pyproject.toml
application/cratedb-toolkit/requirements-test.txt
application/cratedb-toolkit/requirements.txt
application/cratedb-toolkit/test_io.py

Validate CTK's MongoDB Table Loader by importing data from https://github.com/ozlerhakan/mongodb-json-files.

CTK: Validate MongoDB Table Loader

---

topic/machine-learning/llm-langchain/vector_search.py

Fix integration tests with LangChain.
- GH-580

ML/LangChain: Fix standalone `vector_search.py` example program

---

topic/machine-learning/llm-langchain/requirements.txt

What the title says.
- https://github.com/crate-workbench/langchain/issues/25

ML/LangChain: Remove runtime dependency on cratedb-toolkit

---

.github/workflows/ml-langchain.yml

ML/LangChain: Verify on CI using Python 3.12

---

framework/gradio/requirements-dev.txt

Framework/Gradio: Permit updating to gradio-client 1.4

---

topic/machine-learning/llm-langchain/requirements.txt

LangChain v0.3 has been released the other day.
- https://blog.langchain.dev/announcing-langchain-v0-3/
- https://python.langchain.com/docs/versions/v0_3/

ML/LangChain: Update to LangChain release 0.3.4

---

topic/machine-learning/llm-langchain/document_loader.ipynb
topic/machine-learning/llm-langchain/requirements-dev.txt
topic/machine-learning/llm-langchain/requirements.txt
topic/machine-learning/llm-langchain/test.py
topic/machine-learning/llm-langchain/vector_search.py

- 9801b61465a1 fixes a programming error that prevented signaling execution failures on the notebooks the job verifies.
- 2f5d4f92 fixes relevant shortcomings of the notebooks-under-test that have been revealed right away.
/cc @kneth

ML/LangChain: Fix notebooks and tests

---

topic/machine-learning/llama-index/requirements.txt

Bundle a few dependency updates for LlamaIndex.
- GH-733
- GH-734
- GH-735
- GH-736

ML: Update dependencies for LlamaIndex example

---

.github/workflows/lang-npgsql.yml
by-language/csharp-npgsql/demo.csproj

Npgsql: Update to 8.0.6

---

.github/workflows/lang-npgsql.yml
by-language/csharp-npgsql/demo.csproj

Adding Npgsql version 9.x to the test matrix.

Npgsql: Add version 9.0.1

---

.github/workflows/lang-npgsql.yml

CI: Remove uploading coverage results to Codecov for Npgsql

---

application/apache-superset/data.sql

Updated the dataset URLs in `COPY FROM` statements.

Updated dataset URLs in COPY FROM statements.

---

topic/chatbot/Building a PDF Knowledge Assistant- Step by Step.md

Added this to the examples repo
@simonprickett I created this. Can you please check and merge if okay?!

Create Building a PDF Knowledge Assistant- Step by Step.md

---

by-language/python-pg8000/README.rst
by-language/python-pg8000/basic.py

Adds a new example showing how to use prepared statements with CrateDB

Example showing prepared statements with pg8000

---

.github/workflows/lang-r.yml
by-language/r/.gitignore
by-language/r/Makefile
by-language/r/README.md
by-language/r/backlog.md
by-language/r/basic.r

Add minimal example using the R programming language together with the [RPostgreSQL](https://cran.r-project.org/web/packages/RPostgreSQL/) package.

R: Add minimal example

---

.github/dependabot.yml
.github/workflows/lang-elixir-postgrex.yml
by-language/elixir-postgrex/.gitignore
by-language/elixir-postgrex/README.md
by-language/elixir-postgrex/backlog.md
by-language/elixir-postgrex/mix.exs
by-language/elixir-postgrex/test/basic_test.exs
by-language/elixir-postgrex/test/test_helper.exs

Add minimal example using the Elixir programming language together with the [Postgrex](https://hexdocs.pm/postgrex/) package.

Elixir: Add minimal example

---

testing/testcontainers/java/README.rst
testing/testcontainers/java/src/test/java/io/crate/example/testing/TestClassScope.java
testing/testcontainers/java/src/test/java/io/crate/example/testing/TestFunctionScope.java
testing/testcontainers/java/src/test/java/io/crate/example/testing/TestJdbcUrlScheme.java
testing/testcontainers/java/src/test/java/io/crate/example/testing/TestSqlInitialization.java

Use CrateDB 5.10 and PostgreSQL 17.
_Not **every** thing is automatic. /cc @kneth_

Testcontainers for Java: Update software versions

---

framework/dbt/materialize/models/example/jobslog.sql
framework/dbt/materialize/tests/test.yml

This works around https://github.com/crate/dbt-cratedb2/issues/10#issuecomment-2747796826

Improve dbt materialization example

---

framework/mcp/example_dbhub.py
framework/mcp/test.py

Update to most recent version of `@bytebase/dbhub`.
- New resource `db://schemas`
- New argument `schema` for prompt `generate_sql`
- New arguments `schema` and `table` for prompt `explain_db`
- GH-868

MCP: Update to `@bytebase/dbhub@0.2.3`

---

framework/mcp/requirements.txt

MCP Alchemy is now available on PyPI. Thanks, @runekaagaard!
https://pypi.org/project/mcp-alchemy/
- https://github.com/crate/cratedb-toolkit/pull/395

MCP: Update to `mcp-alchemy` GA from PyPI

---

framework/mcp/README.md
framework/mcp/example_dbhub.py
framework/mcp/example_mcp_alchemy.py
framework/mcp/requirements.txt

MCP: Maintenance 2025W16

---

application/cratedb-toolkit/test_io.py
framework/mcp/example_builtin.py
framework/mcp/example_cratedb_mcp.py
framework/mcp/example_dbhub.py
framework/mcp/example_mcp_alchemy.py
framework/mcp/example_pg_mcp.py
framework/mcp/test.py
topic/machine-learning/automl/test.py
topic/machine-learning/llm-langchain/document_loader.ipynb
topic/machine-learning/llm-langchain/document_loader.py
topic/machine-learning/mlops-mlflow/test.py

Accompanying another little maintenance patch.
- https://github.com/crate/cratedb-toolkit/pull/414

Maintenance: Update module references for CTK's `DatabaseAdapter`

---

framework/records/README.md

Fix CrateDB Cloud URI

---

framework/dlt/basic.py
framework/dlt/pokemon.py
framework/dlt/requirements.txt
framework/dlt/test.py

dlt adjustments

---

.github/dependabot.yml
.github/workflows/application-llm.yml
application/llm/README.md
application/llm/requirements.txt
application/llm/test.xsh

[llm](https://pypi.org/project/llm/) is truly a gem, let's give it a dedicated slot here.
We may want to prefer it instead of custom chat wrappers like `cratedb-about ask` or [CrateDB Marvin Assistant](https://github.com/WalBeh/marvin_cratedb_mcp).

LLM: Add demo about using `llm`
